# Generated by Django 4.1 on 2023-07-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bngjobs',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='eligibility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='eligibility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='eligibility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
